AMCP Sandbox/force-app/main/default/objects/SSOCustomFields__mdt/SSOCustomFields__mdt.object-meta.xml
<CustomObject>
    <label>SSOCustomField</label>
    <pluralLabel>SSOCustomFields</pluralLabel>
</CustomObject>

force-app/main/default/objects/SSOCustomFields__mdt/fields/AttributeKey__c.field-meta.xml
<CustomField>
    <fullName>AttributeKey__c</fullName>
    <description>The key to which the custom fields values are added. This will be used on the service provider for looking up values</description>
    <inlineHelpText>The key to which the custom fields values are added. This will be used on the service provider for looking up values</inlineHelpText>
    <label>AttributeKey</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSOCustomFields__mdt/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <description>Add the exact apiname of the field that needs to be added to custom attribute</description>
    <inlineHelpText>Add the exact apiname of the field that needs to be added to custom attribute</inlineHelpText>
    <label>FieldApiName</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SSOCustomFields__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <description>Object Name from which the custom fields are added to SSO. Add the exact apiName of the object</description>
    <inlineHelpText>Object Name from which the custom fields are added to SSO. Add the exact apiName of the object</inlineHelpText>
    <label>ObjectName</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
                <default>true</default>
                <label>User</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomAttributeLoader.cls
public inherited sharing class CustomAttributeLoader {

  public static CustomAttributeLoader getInstance(Id userId, Id connectedAppId, Auth.InvocationContext context){
    return new CustomAttributeLoader(new SSOMetadataFetcherImpl(), userId);
  }

  private SSOMetadataFetcher metadataFetcher;
  private Id userId;
  public CustomAttributeLoader(SSOMetadataFetcher metadataFetcher, Id userId){
    this.metadataFetcher = metadataFetcher;
    this.userId = userId;
  }

  public Map<String, String> augmentCustomAttributes(Map<String, String> formulaDefinedAttributes){
    List<SSOCustomFields__mdt> ssoCustomFieldsByIds = metadataFetcher.getSSOCustomFieldsByIds();

    User user = fetchUser(ssoCustomFieldsByIds);

    Contact contact = fetchContact(ssoCustomFieldsByIds, user);

    for(SSOCustomFields__mdt customField : ssoCustomFieldsByIds){
      if(customField.ObjectName__c == 'User'){
        formulaDefinedAttributes.put(customField.AttributeKey__c, String.valueOf(user.get(customField.FieldApiName__c)));
      } else if(customField.ObjectName__c == 'Contact'){
        formulaDefinedAttributes.put(customField.AttributeKey__c, String.valueOf(contact.get(customField.FieldApiName__c)));
      }
    }

    return formulaDefinedAttributes;
  }

  private User fetchUser(List<SSOCustomFields__mdt> ssoCustomFieldsByIds) {
    String userQuery = 'SELECT Id, ContactId,';
    String userFields = '';

    for (SSOCustomFields__mdt customField : ssoCustomFieldsByIds) {
      if (customField.ObjectName__c == 'User') {
        userFields += customField.FieldApiName__c + ',';
      }
    }
    userQuery += userFields;
    userQuery = userQuery.removeEnd(',');
    userQuery += ' FROM User WHERE Id = \'' + userId + '\'';

    User user = Database.query(userQuery);
    return user;
  }

  private Contact fetchContact(List<SSOCustomFields__mdt> ssoCustomFieldsByIds, User user) {
    String contactFields = '';

    for (SSOCustomFields__mdt customField : ssoCustomFieldsByIds) {
      if (customField.ObjectName__c == 'Contact') {
        contactFields += 'Contact.' + customField.FieldApiName__c + ',';
      }
    }

    String contactQuery = 'SELECT Id,';
    contactQuery += contactFields;
    contactQuery = contactQuery.removeEnd(',');
    contactQuery += ' FROM Contact WHERE Id = \'' + user.ContactId + '\'';

    Contact contact = Database.query(contactQuery);
    return contact;
  }

}