force-app/main/default/objects/Engagement_Score_Snapshot__c/Engagement_Score_Snapshot__c.object-meta.xml
<CustomObject>
    <description>Custom object to hold contact engagement score snapshot report</description>
    <label>Engagement Score Snapshot</label>
    <nameField>
        <displayFormat>EngagementSnapshot-{0000}</displayFormat>
        <label>Engagement Score Snapshot  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Score Snapshots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/AMCP_Learn_Certificate__c.field-meta.xml
<CustomField>
    <fullName>AMCP_Learn_Certificate__c</fullName>
    <label>AMCP Learn Certificate</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/AMCP_Learn_Products__c.field-meta.xml
<CustomField>
    <fullName>AMCP_Learn_Products__c</fullName>
    <label>AMCP Learn Products</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/AMCP_Webinar_Score__c.field-meta.xml
<CustomField>
    <fullName>AMCP_Webinar_Score__c</fullName>
    <label>AMCP Webinar Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Board_Committee_Score__c.field-meta.xml
<CustomField>
    <fullName>Board_Committee_Score__c</fullName>
    <label>Leadership</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/CE_Webinar_Score__c.field-meta.xml
<CustomField>
    <fullName>CE_Webinar_Score__c</fullName>
    <label>CE Webinar Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Champion_Score__c.field-meta.xml
<CustomField>
    <fullName>Champion_Score__c</fullName>
    <label>Champion Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Engagement Score Snapshots</relationshipLabel>
    <relationshipName>Engagement_Score_Snapshots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Donation_Score__c.field-meta.xml
<CustomField>
    <fullName>Donation_Score__c</fullName>
    <label>Donation Score</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Engagement_Category__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Category__c</fullName>
    <label>Engagement Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Meeting_Affiliate_Score__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Affiliate_Score__c</fullName>
    <label>Meeting-Affiliate Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Meeting_Virtual__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Virtual__c</fullName>
    <label>Meeting – Virtual</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Meetings_Large_Score__c.field-meta.xml
<CustomField>
    <fullName>Meetings_Large_Score__c</fullName>
    <label>Meetings-Large Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Meetings_Small_Score__c.field-meta.xml
<CustomField>
    <fullName>Meetings_Small_Score__c</fullName>
    <label>Meetings-Small Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Membership_Engagement_Score__c.field-meta.xml
<CustomField>
    <fullName>Membership_Engagement_Score__c</fullName>
    <label>Membership</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Overall_Engagement_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Engagement_Score__c</fullName>
    <description>This will have the engagement score on a particular day</description>
    <label>Overall Engagement Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/PIE_Webinar_Score__c.field-meta.xml
<CustomField>
    <fullName>PIE_Webinar_Score__c</fullName>
    <label>PIE Webinar Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/SIT_Webinar_Score__c.field-meta.xml
<CustomField>
    <fullName>SIT_Webinar_Score__c</fullName>
    <label>SIT Webinar Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Volunteer_Long_Term_Score__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Long_Term_Score__c</fullName>
    <label>Volunteer - Long Term Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Volunteer_Short_Term_Score__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Short_Term_Score__c</fullName>
    <label>Volunteer Short Term Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Engagement_Score_Snapshot__c/fields/Webinar_Score__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Score__c</fullName>
    <label>Webinar Score</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaptureEngagementScoreHistoryBatch.cls
global class CaptureEngagementScoreHistoryBatch implements Database.Batchable<sObject>, Database.Stateful {
    global String contactId;
    global Database.QueryLocator start(Database.BatchableContext BC) {        
        List<String> fieldsApiNames = getFieldNames();
        String query = 'SELECT Id, ' + String.join(fieldsApiNames, ',') + ' FROM Contact';
        if(contactId !=null){
            query = 'SELECT Id, ' + String.join(fieldsApiNames, ',') + ' FROM Contact WHERE Id =:contactId';
        }
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Contact> contacts) {
        List<Engagement_Score_Snapshot__c> essList = new List<Engagement_Score_Snapshot__c>();

        for(Contact contact: contacts){
            Engagement_Score_Snapshot__c ess = getEngagementScoreSnapshot(contact);
            essList.add(ess);
        }
        insert essList;
    }   
    global void finish(Database.BatchableContext BC) {
    }

    public static Engagement_Score_Snapshot__c getEngagementScoreSnapshot(Contact contact){
        Engagement_Score_Snapshot__c ess = new Engagement_Score_Snapshot__c();
        ess.Contact__c = contact.Id;
        ess.Engagement_Category__c = contact.Engagement_Category__c;
        ess.Overall_Engagement_Score__c = contact.Overall_Engagement_Score__c;
        ess.Membership_Engagement_Score__c = contact.Membership_Score__c;
        ess.Board_Committee_Score__c = contact.Board_Committee_Score__c;
        ess.Meetings_Large_Score__c = contact.Meetings_Large_Score__c;
        ess.Meetings_Small_Score__c = contact.Meetings_Small__c;
        ess.Meeting_Affiliate_Score__c = contact.Affiliate_Meetings__c;
        ess.AMCP_Webinar_Score__c = contact.AMCP_Webinar__c;
        ess.CE_Webinar_Score__c = contact.CE_Webinar__c;
        ess.PIE_Webinar_Score__c = contact.PIE_Webinar__c;
        ess.SIT_Webinar_Score__c = contact.SIT_Webinar__c;
        ess.Meeting_Virtual__c = contact.Virtual_Meetings__c;
        ess.AMCP_Learn_Products__c = contact.Learn_Product_Score__c;
        ess.AMCP_Learn_Certificate__c = contact.Ethos_Certification_Score__c;
        ess.Webinar_Score__c = contact.Webinar_Score__c;
        ess.Volunteer_Long_Term_Score__c = contact.Volunteer_Long_Term_Score__c;
        ess.Volunteer_Short_Term_Score__c = contact.Volunteer_Short_Term_Score__c;
        ess.Donation_Score__c = contact.Donation_Score__c;
        ess.Champion_Score__c = contact.Champion__c;

        return ess;
    }
    public static List<String>  getFieldNames(){
        List<String> fieldsApiNames = new List<String>();
        fieldsApiNames.add('Engagement_Category__c');
        fieldsApiNames.add('Overall_Engagement_Score__c');
        fieldsApiNames.add('OrderApi__Lifetime_Engagement_Score__c');
        fieldsApiNames.add('Board_Score__c');
        fieldsApiNames.add('Meetings_Small__c');
        fieldsApiNames.add('Meetings_Large_Score__c');
        fieldsApiNames.add('Affiliate_Meetings__c');
        fieldsApiNames.add('AMCP_Webinar__c');
        fieldsApiNames.add('CE_Webinar__c');
        fieldsApiNames.add('PIE_Webinar__c');
        fieldsApiNames.add('SIT_Webinar__c');
        fieldsApiNames.add('Virtual_Meetings__c');
        fieldsApiNames.add('Learn_Product_Score__c');
        fieldsApiNames.add('Learn_Product_Participation_Score__c');
        fieldsApiNames.add('Webinar_Score__c');
        fieldsApiNames.add('Volunteer_Long_Term_Score__c');
        fieldsApiNames.add('Volunteer_Short_Term_Score__c');
        fieldsApiNames.add('Donation_Score__c');
        fieldsApiNames.add('Champion__c');
        fieldsApiNames.add('Membership_Score__c');
        fieldsApiNames.add('Board_Committee_Score__c');
        fieldsApiNames.add('Ethos_Certification_Score__c');
        
        return fieldsApiNames;
    }
}